pipeline:
  frontend:
    image: mhart/alpine-node:4.7.2
    commands:
      - cd webapp
      - apk add --no-cache make gcc g++ python
      - npm install gulp-cli -g --silent
      - npm install
      - npm cache clean
      - gulp build
      - echo '- BUILD DONE -'

   slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: notion
    username: drone
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}

  deploy-fe:
    environment:
      BUILD_NUM: $$COMMIT
      ENV_NAME: 'dev'
    action: update
    image: nytimes/drone-gae
    project: &sudo-marketing-notion
    app_file: webapp/app.yaml
    version: abc123
    ae_environment:
      APP_NAME: sudo-marketing-notion
      ENV_NAME: 'dev'
    when:
      event: push
    secrets:
      - source: sudo_marketing_notion_google_creds
        target: gae_credentials

    # gae:
    #   image: nytimes/drone-gae
    #   action: set_default_version
    #   project: sudo-marketing
    #   app_file: app.yaml
    #   version: "$$COMMIT"
    #   token: >
    #     $$GOOGLE_CREDENTIALS
    #   when:
    #     event: push
