pipeline:
  frontend:
    image: mhart/alpine-node:4.7.2
    commands:
      - cd webapp
      - apk add --no-cache make gcc g++ python
      - npm install gulp-cli -g --silent
      - npm install
      - npm cache clean
      - gulp build
      - echo '- BUILD DONE -'

  deploy-fe:
    environment:
      BUILD_NUM: ${COMMIT}
      ENV_NAME: 'dev'
    action: update
    image: nytimes/drone-gae
    project: &sudo-marketing-notion
    app_file: webapp/app.yaml
    version: COD # ${COMMIT}
    ae_environment:
      APP_NAME: sudo-marketing-notion
      ENV_NAME: 'dev'
    when:
      event: push
    secrets:
      - source: sudo_marketing_notion_google_creds
        target: gae_credentials
    fe-switch-traffic:
      image: nytimes/drone-gae
      action: set_default_version
      project: &sudo-marketing-notion
      app_file: webapp/app.yaml
      version: COD # ${COMMIT}
    secrets:
      - source: sudo_marketing_notion_google_creds
        target: gae_credentials
      when:
        event: push


  # deploy-be:
  #   environment:
  #     BUILD_NUM: $$COMMIT
  #     ENV_NAME: 'dev'
  #   action: update
  #   image: nytimes/drone-gae
  #   project: &sudo-marketing-notion
  #   app_file: rhizome/app.yaml
  #   version: abc123-be
  #   ae_environment:
  #     APP_NAME: sudo-marketing-notion
  #     ENV_NAME: 'dev'
  #   when:
  #     event: push
  #   secrets:
  #     - source: sudo_marketing_notion_google_creds
  #       target: gae_credentials
