runtime: python27
api_version: 1
threadsafe: true
service: notion-fe

instance_class: F2
automatic_scaling:
  min_idle_instances: 0
  max_concurrent_requests: 10

handlers:
- url: /public/static/
  static_dir: webapp/public/static/
  login: admin
- url: /charts
  static_files: webapp/public/templates/charts/index.html
  upload: webapp/public/templates/charts/index.html
  secure: always
- url: /charts/create
  static_files: webapp/public/templates/charts/create.html
  upload: webapp/public/templates/charts/create.html
  secure: always
- url: /dashboards
  static_files: webapp/public/templates/dashboards/index.html
  upload: webapp/public/templates/dashboards/index.html
  secure: always
- url: /
  static_files: webapp/public/templates/index.html
  upload: webapp/public/templates/index.html
  secure: always


env_variables:
  GAE_USE_SOCKETS_HTTPLIB: 'true'

libraries:
- name: pycrypto
  version: '2.6'
- name: ssl
  version: latest

skip_files:
- ^(.*/)?.*/node_modules/.*$
- ^(node_modules/.*)
- ^(.*/)?.*\.py[co]$
