runtime: python27
api_version: 1
threadsafe: true
module: default

instance_class: F2
automatic_scaling:
  min_idle_instances: 0
  max_concurrent_requests: 10

handlers:
- url: /0.1/(.*)
  script: main.app
  secure: always
- url: /index.html
  static_files: index.html
  upload: index.html
  secure: always

env_variables:
  GAE_USE_SOCKETS_HTTPLIB: 'true'

libraries:
- name: pycrypto
  version: '2.6'
- name: ssl
  version: latest
